version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CREATE_TOPICS: "TEST1:1:3,TEST2:1:1:compact"
      KAFKA_ADVERTISED_HOST_NAME: kafka

      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      KAFKA_LISTENER_INTERNAL_PORT: 9092
      KAFKA_LISTENERS_INTERNAL: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS_INTERNAL: INTERNAL://kafka:9092

      # KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      # KAFKA_LISTENER_EXTERNAL_PORT: 9093
      # KAFKA_LISTENERS_EXTERNAL: EXTERNAL://0.0.0.0:9093
      # KAFKA_ADVERTISED_LISTENERS_EXTERNAL: EXTERNAL://kafka:9093
      # KAFKA_LISTENER_SECURITY_PROTOCOL_EXTERNAL: PLAINTEXT

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      # - "9093:9093"
      - "9092:9092"
    networks:
      - kafka-net
    depends_on:
      - zookeeper
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    ports:
      - "8080:8080"
    networks:
      - kafka-net
    restart: always

networks:
  kafka-net:
    driver: bridge
